// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fasta.proto

/*
Package gbparse is a generated protocol buffer package.

It is generated from these files:
	fasta.proto
	genbank.proto

It has these top-level messages:
	Fasta
	Genbank
	Reference
	Feature
	Qualifier
*/
package gbparse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Fasta struct {
	HEADER    string `protobuf:"bytes,1,opt,name=HEADER" json:"HEADER,omitempty"`
	ACCESSION string `protobuf:"bytes,2,opt,name=ACCESSION" json:"ACCESSION,omitempty"`
	VERSION   string `protobuf:"bytes,3,opt,name=VERSION" json:"VERSION,omitempty"`
	SEQUENCE  string `protobuf:"bytes,4,opt,name=SEQUENCE" json:"SEQUENCE,omitempty"`
}

func (m *Fasta) Reset()                    { *m = Fasta{} }
func (m *Fasta) String() string            { return proto.CompactTextString(m) }
func (*Fasta) ProtoMessage()               {}
func (*Fasta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Fasta) GetHEADER() string {
	if m != nil {
		return m.HEADER
	}
	return ""
}

func (m *Fasta) GetACCESSION() string {
	if m != nil {
		return m.ACCESSION
	}
	return ""
}

func (m *Fasta) GetVERSION() string {
	if m != nil {
		return m.VERSION
	}
	return ""
}

func (m *Fasta) GetSEQUENCE() string {
	if m != nil {
		return m.SEQUENCE
	}
	return ""
}

func init() {
	proto.RegisterType((*Fasta)(nil), "gbparse.Fasta")
}

func init() { proto.RegisterFile("fasta.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4b, 0x2c, 0x2e,
	0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4f, 0x2a, 0x48, 0x2c, 0x2a, 0x4e,
	0x55, 0x2a, 0xe6, 0x62, 0x75, 0x03, 0x89, 0x0b, 0x89, 0x71, 0xb1, 0x79, 0xb8, 0x3a, 0xba, 0xb8,
	0x06, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x32, 0x5c, 0x9c, 0x8e, 0xce,
	0xce, 0xae, 0xc1, 0xc1, 0x9e, 0xfe, 0x7e, 0x12, 0x4c, 0x60, 0x29, 0x84, 0x80, 0x90, 0x04, 0x17,
	0x7b, 0x98, 0x6b, 0x10, 0x58, 0x8e, 0x19, 0x2c, 0x07, 0xe3, 0x0a, 0x49, 0x71, 0x71, 0x04, 0xbb,
	0x06, 0x86, 0xba, 0xfa, 0x39, 0xbb, 0x4a, 0xb0, 0x80, 0xa5, 0xe0, 0xfc, 0x24, 0x36, 0xb0, 0x23,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xa3, 0x9c, 0x16, 0x93, 0x00, 0x00, 0x00,
}
