// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genbank.proto

package gbparse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Genbank struct {
	LOCUS      string       `protobuf:"bytes,1,opt,name=LOCUS" json:"LOCUS,omitempty"`
	ACCESSION  []string     `protobuf:"bytes,2,rep,name=ACCESSION" json:"ACCESSION,omitempty"`
	DEFINITION string       `protobuf:"bytes,3,opt,name=DEFINITION" json:"DEFINITION,omitempty"`
	VERSION    string       `protobuf:"bytes,4,opt,name=VERSION" json:"VERSION,omitempty"`
	DBLINK     []string     `protobuf:"bytes,5,rep,name=DBLINK" json:"DBLINK,omitempty"`
	KEYWORDS   string       `protobuf:"bytes,6,opt,name=KEYWORDS" json:"KEYWORDS,omitempty"`
	SOURCE     string       `protobuf:"bytes,7,opt,name=SOURCE" json:"SOURCE,omitempty"`
	ORGANISM   []string     `protobuf:"bytes,8,rep,name=ORGANISM" json:"ORGANISM,omitempty"`
	COMMENT    string       `protobuf:"bytes,9,opt,name=COMMENT" json:"COMMENT,omitempty"`
	SEQUENCE   string       `protobuf:"bytes,10,opt,name=SEQUENCE" json:"SEQUENCE,omitempty"`
	CONTIG     string       `protobuf:"bytes,11,opt,name=CONTIG" json:"CONTIG,omitempty"`
	REFERENCES []*Reference `protobuf:"bytes,12,rep,name=REFERENCES" json:"REFERENCES,omitempty"`
	FEATURES   []*Feature   `protobuf:"bytes,13,rep,name=FEATURES" json:"FEATURES,omitempty"`
}

func (m *Genbank) Reset()                    { *m = Genbank{} }
func (m *Genbank) String() string            { return proto.CompactTextString(m) }
func (*Genbank) ProtoMessage()               {}
func (*Genbank) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Genbank) GetLOCUS() string {
	if m != nil {
		return m.LOCUS
	}
	return ""
}

func (m *Genbank) GetACCESSION() []string {
	if m != nil {
		return m.ACCESSION
	}
	return nil
}

func (m *Genbank) GetDEFINITION() string {
	if m != nil {
		return m.DEFINITION
	}
	return ""
}

func (m *Genbank) GetVERSION() string {
	if m != nil {
		return m.VERSION
	}
	return ""
}

func (m *Genbank) GetDBLINK() []string {
	if m != nil {
		return m.DBLINK
	}
	return nil
}

func (m *Genbank) GetKEYWORDS() string {
	if m != nil {
		return m.KEYWORDS
	}
	return ""
}

func (m *Genbank) GetSOURCE() string {
	if m != nil {
		return m.SOURCE
	}
	return ""
}

func (m *Genbank) GetORGANISM() []string {
	if m != nil {
		return m.ORGANISM
	}
	return nil
}

func (m *Genbank) GetCOMMENT() string {
	if m != nil {
		return m.COMMENT
	}
	return ""
}

func (m *Genbank) GetSEQUENCE() string {
	if m != nil {
		return m.SEQUENCE
	}
	return ""
}

func (m *Genbank) GetCONTIG() string {
	if m != nil {
		return m.CONTIG
	}
	return ""
}

func (m *Genbank) GetREFERENCES() []*Reference {
	if m != nil {
		return m.REFERENCES
	}
	return nil
}

func (m *Genbank) GetFEATURES() []*Feature {
	if m != nil {
		return m.FEATURES
	}
	return nil
}

type Reference struct {
	Number  int32  `protobuf:"varint,1,opt,name=Number" json:"Number,omitempty"`
	ORIGIN  string `protobuf:"bytes,2,opt,name=ORIGIN" json:"ORIGIN,omitempty"`
	AUTHORS string `protobuf:"bytes,3,opt,name=AUTHORS" json:"AUTHORS,omitempty"`
	CONSRTM string `protobuf:"bytes,4,opt,name=CONSRTM" json:"CONSRTM,omitempty"`
	TITLE   string `protobuf:"bytes,5,opt,name=TITLE" json:"TITLE,omitempty"`
	JOURNAL string `protobuf:"bytes,6,opt,name=JOURNAL" json:"JOURNAL,omitempty"`
	PUBMED  string `protobuf:"bytes,7,opt,name=PUBMED" json:"PUBMED,omitempty"`
}

func (m *Reference) Reset()                    { *m = Reference{} }
func (m *Reference) String() string            { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()               {}
func (*Reference) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Reference) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Reference) GetORIGIN() string {
	if m != nil {
		return m.ORIGIN
	}
	return ""
}

func (m *Reference) GetAUTHORS() string {
	if m != nil {
		return m.AUTHORS
	}
	return ""
}

func (m *Reference) GetCONSRTM() string {
	if m != nil {
		return m.CONSRTM
	}
	return ""
}

func (m *Reference) GetTITLE() string {
	if m != nil {
		return m.TITLE
	}
	return ""
}

func (m *Reference) GetJOURNAL() string {
	if m != nil {
		return m.JOURNAL
	}
	return ""
}

func (m *Reference) GetPUBMED() string {
	if m != nil {
		return m.PUBMED
	}
	return ""
}

type Feature struct {
	TYPE         string       `protobuf:"bytes,1,opt,name=TYPE" json:"TYPE,omitempty"`
	IsCompliment bool         `protobuf:"varint,2,opt,name=isCompliment" json:"isCompliment,omitempty"`
	IsJoined     bool         `protobuf:"varint,3,opt,name=isJoined" json:"isJoined,omitempty"`
	START        string       `protobuf:"bytes,4,opt,name=START" json:"START,omitempty"`
	STOP         string       `protobuf:"bytes,5,opt,name=STOP" json:"STOP,omitempty"`
	QUALIFIERS   []*Qualifier `protobuf:"bytes,6,rep,name=QUALIFIERS" json:"QUALIFIERS,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Feature) GetTYPE() string {
	if m != nil {
		return m.TYPE
	}
	return ""
}

func (m *Feature) GetIsCompliment() bool {
	if m != nil {
		return m.IsCompliment
	}
	return false
}

func (m *Feature) GetIsJoined() bool {
	if m != nil {
		return m.IsJoined
	}
	return false
}

func (m *Feature) GetSTART() string {
	if m != nil {
		return m.START
	}
	return ""
}

func (m *Feature) GetSTOP() string {
	if m != nil {
		return m.STOP
	}
	return ""
}

func (m *Feature) GetQUALIFIERS() []*Qualifier {
	if m != nil {
		return m.QUALIFIERS
	}
	return nil
}

type Qualifier struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Qualifier) Reset()                    { *m = Qualifier{} }
func (m *Qualifier) String() string            { return proto.CompactTextString(m) }
func (*Qualifier) ProtoMessage()               {}
func (*Qualifier) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Qualifier) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Qualifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Genbank)(nil), "gbparse.Genbank")
	proto.RegisterType((*Reference)(nil), "gbparse.Reference")
	proto.RegisterType((*Feature)(nil), "gbparse.Feature")
	proto.RegisterType((*Qualifier)(nil), "gbparse.Qualifier")
}

func init() { proto.RegisterFile("genbank.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x93, 0x4f, 0x6e, 0xdb, 0x3c,
	0x10, 0xc5, 0xe1, 0xcf, 0xf1, 0x1f, 0x31, 0x09, 0x10, 0x10, 0x1f, 0x0a, 0xa2, 0x28, 0x0a, 0xc3,
	0x2b, 0x2f, 0x0a, 0x2f, 0x92, 0x13, 0x28, 0x32, 0xed, 0x32, 0x91, 0x48, 0x7b, 0x48, 0xb5, 0xc8,
	0x52, 0x6e, 0x99, 0x40, 0x88, 0x2d, 0x1b, 0xb2, 0x5d, 0xa0, 0xa7, 0xe8, 0x71, 0xba, 0xe8, 0xe5,
	0x8a, 0x21, 0x29, 0xd5, 0xd9, 0xf1, 0xc7, 0x99, 0xc7, 0x79, 0xe4, 0x93, 0xc8, 0xf5, 0x8b, 0xad,
	0xd6, 0x45, 0xf5, 0x3a, 0xdd, 0xd7, 0xbb, 0xe3, 0x8e, 0x0e, 0x5e, 0xd6, 0xfb, 0xa2, 0x3e, 0xd8,
	0xf1, 0xaf, 0x2e, 0x19, 0x2c, 0x7c, 0x89, 0xfe, 0x4f, 0x7a, 0xa9, 0x4a, 0x72, 0xcd, 0x3a, 0xa3,
	0xce, 0x24, 0x02, 0x0f, 0xf4, 0x03, 0x89, 0xe2, 0x24, 0xe1, 0x5a, 0x0b, 0x25, 0xd9, 0x7f, 0xa3,
	0xee, 0x24, 0x82, 0x7f, 0x1b, 0xf4, 0x23, 0x21, 0x33, 0x3e, 0x17, 0x52, 0x18, 0x2c, 0x77, 0x9d,
	0xf0, 0x6c, 0x87, 0x32, 0x32, 0xf8, 0xc2, 0xc1, 0x69, 0x2f, 0x5c, 0xb1, 0x41, 0xfa, 0x8e, 0xf4,
	0x67, 0xf7, 0xa9, 0x90, 0x8f, 0xac, 0xe7, 0x0e, 0x0d, 0x44, 0xdf, 0x93, 0xe1, 0x23, 0x7f, 0xfa,
	0xaa, 0x60, 0xa6, 0x59, 0xdf, 0x49, 0x5a, 0x46, 0x8d, 0x56, 0x39, 0x24, 0x9c, 0x0d, 0x5c, 0x25,
	0x10, 0x6a, 0x14, 0x2c, 0x62, 0x29, 0x74, 0xc6, 0x86, 0xee, 0xb4, 0x96, 0xd1, 0x41, 0xa2, 0xb2,
	0x8c, 0x4b, 0xc3, 0x22, 0xef, 0x20, 0x20, 0xaa, 0x34, 0x5f, 0xe5, 0x5c, 0x26, 0x9c, 0x11, 0x3f,
	0xa9, 0x61, 0x9c, 0x94, 0x28, 0x69, 0xc4, 0x82, 0x5d, 0xfa, 0x49, 0x9e, 0xe8, 0x2d, 0x21, 0xc0,
	0xe7, 0x1c, 0xb0, 0x49, 0xb3, 0xab, 0x51, 0x77, 0x72, 0x79, 0x4b, 0xa7, 0xe1, 0x35, 0xa7, 0x60,
	0x9f, 0x6d, 0x6d, 0xab, 0x6f, 0x16, 0xce, 0xba, 0xe8, 0x27, 0x32, 0x9c, 0xf3, 0xd8, 0xe4, 0xc0,
	0x35, 0xbb, 0x76, 0x8a, 0x9b, 0x56, 0x31, 0xb7, 0xc5, 0xf1, 0x54, 0x5b, 0x68, 0x3b, 0xc6, 0xbf,
	0x3b, 0x24, 0x6a, 0xcf, 0x41, 0x1f, 0xf2, 0xb4, 0x5d, 0xdb, 0xda, 0x85, 0xd2, 0x83, 0x40, 0xb8,
	0xaf, 0x40, 0x2c, 0x04, 0x46, 0xe2, 0xfc, 0x79, 0xc2, 0xdb, 0xc6, 0xb9, 0xf9, 0xac, 0x40, 0x87,
	0x30, 0x1a, 0xf4, 0xef, 0x20, 0x35, 0x98, 0xac, 0x49, 0x22, 0x20, 0xe6, 0x6e, 0x84, 0x49, 0x39,
	0xeb, 0xf9, 0xdc, 0x1d, 0x60, 0xff, 0x83, 0xca, 0x41, 0xc6, 0x69, 0x88, 0xa1, 0x41, 0x9c, 0xbd,
	0xcc, 0xef, 0x33, 0x3e, 0x6b, 0x52, 0xf0, 0x34, 0xfe, 0xd3, 0x21, 0x83, 0x70, 0x1f, 0x4a, 0xc9,
	0x85, 0x79, 0x5a, 0xf2, 0xf0, 0x29, 0xb9, 0x35, 0x1d, 0x93, 0xab, 0xf2, 0x90, 0xec, 0xb6, 0xfb,
	0x4d, 0xb9, 0xb5, 0xd5, 0xd1, 0x39, 0x1f, 0xc2, 0x9b, 0x3d, 0xcc, 0xa4, 0x3c, 0x3c, 0xec, 0xca,
	0xca, 0x7e, 0x77, 0x17, 0x18, 0x42, 0xcb, 0xe8, 0x53, 0x9b, 0x18, 0x4c, 0xf0, 0xef, 0x01, 0x27,
	0x69, 0xa3, 0x96, 0xc1, 0xbc, 0x5b, 0x63, 0x4a, 0xab, 0x3c, 0x4e, 0xc5, 0x5c, 0x70, 0xc0, 0xaf,
	0xe8, 0x6d, 0x4a, 0xab, 0x53, 0xb1, 0x29, 0x9f, 0x4b, 0x5b, 0xc3, 0x59, 0xd7, 0xf8, 0x8e, 0x44,
	0x6d, 0x81, 0xde, 0x90, 0xee, 0xab, 0xfd, 0x19, 0xdc, 0xe3, 0x12, 0x87, 0xff, 0x28, 0x36, 0x27,
	0x1b, 0xde, 0xdb, 0xc3, 0xba, 0xef, 0x7e, 0xa7, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x57,
	0x51, 0xb7, 0xc8, 0x5f, 0x03, 0x00, 0x00,
}
